Repository MY-SOPT-IN/MY-SOPT-IN-iOS, pull requests merged in 2023-05, with the labels that each got.

#3 [Test] #1 테스트 커밋입니당
  .gitignore
Labels: 성우 🫥

#6 [Feat] #5 커스텀 탭바 구현
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Application/SceneDelegate.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TabBar/TabBarController.swift
Labels: 다예 👐🏻

#13 Feat/#11 BottomSheet에 따른 View, VC 구현
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Extension/UIButton+.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Extension/UILabel+.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Extension/UIView+.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Literal/ImageLiteral.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/AlertImage/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/AlertImage/alert.imageset/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/AlertImage/alert.imageset/alert.svg
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/BottomSheet_ic/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/BottomSheet_ic/add_ic_addButton.imageset/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/BottomSheet_ic/add_ic_addButton.imageset/add_ic_addButton.svg
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/Routine/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/Routine/add_ic_vector.imageset/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/Routine/add_ic_vector.imageset/add_ic_vector.svg
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/Routine/calender.imageset/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/Routine/calender.imageset/calender.svg
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/Routine/question.imageset/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/Routine/question.imageset/question.svg
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/navigationbar/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/Component/Customnavigationbar.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/AddRoutineViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/BottomSheetViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/CustomAlertViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/EditRoutineViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/BottomSheetView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/RoutineView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RetrospectPage/VC/RetrospectViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RetrospectPage/View/RetrospectView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TabBar/TabBarController.swift
Labels: 성우 🫥

#17 [Hotfix] #16- 충돌 해결
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/AchieveViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TabBar/TabBarController.swift
Labels: 성우 🫥, Fix

#19 Feat/#11 BottomSheet 수정
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Extension/UIButton+.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/Component/Customnavigationbar.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/AddRoutineViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/BottomSheetViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/CustomAlertViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/EditRoutineViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/BottomSheetView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/RoutineView.swift
Labels: 성우 🫥, Design

#22 [Hotfix] #21 코드 누락으로 인한 빌드 오류 수정
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/EditRoutineViewController.swift
Labels: bug, 성우 🫥, Fix

#23 Feat/#18 - Recall View, VC 구현
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Literal/ImageLiteral.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/recall/more.imageset/Contents.json
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Resource/Assets.xcassets/recall/more.imageset/more.png
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/VC/EditRecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/VC/RecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/View/RecallView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TabBar/TabBarController.swift
Labels: 성우 🫥, Design

#26 [Setting] #24 - 서버 초기세팅
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Info.plist
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/API/Retro/RetroAPI.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Config/Config.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/DTO/TotalRetroResponseDTO.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/APIConstants.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/AlamofireLogger.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/BaseAPI.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/BaseResponse.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/BaseTargetType.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/NetworkResult.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Router/Retro/RetroRouter.swift
Labels: 인영🫶🏻, Setting, API 통신

#28 [Feat] #12 메인 페이지 뷰 연결
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageRoutineTVC.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageRoutineViewController.swift
Labels: 다예 👐🏻, Design

#31 Feat/#18 RecallView TableView로 전환
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/Component/Customnavigationbar.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageRecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/MainPageRecallHeaderView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/RoutineView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/VC/EditRecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/VC/RecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/View/RecallFooterView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/View/RecallTableViewCell.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecallPage/View/RecallView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TotalRoutine/VC/TotalRoutineViewController.swift
Labels: 성우 🫥, Design

#34 [Feat] 메인 페이지 자잘한 수정
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Global/Extension/SelectDateCVC.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Model/MainPageRoutineHeaderView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Model/MyDates.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageRecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageRoutineTVC.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageRoutineViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/MainPageRecallHeaderView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/Views/MainPageRoutineBorderView.swift
Labels: 다예 👐🏻, Design

#36 [Feat] #27 - 서버 세팅 수정 및 전체회고 API연결
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS.xcodeproj/project.pbxproj
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/API/Retro/RetroAPI.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/DTO/TotalRetroResponseDTO.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/BaseAPI.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/BaseResponse.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Network/Foundation/BaseTargetType.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/MainPage/VC/MainPageRecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/RecommendRoutine/RecommendRoutineViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TotalRecall/VC/DatePickerViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TotalRecall/VC/TotalRecallViewController.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TotalRecall/Views/DatePickerControl.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TotalRecall/Views/TotalRecallHeaderView.swift
  MY-SOPT-IN-iOS/MY-SOPT-IN-iOS/Presentation/TotalRecall/Views/TotalRecallTableViewCell.swift
Labels: 인영🫶🏻, Setting, API 통신
